version: '3.8'

networks:
  meca-network:
    driver: bridge

volumes:
  mysqldata:

services:

  php:
    build: .
    context: .
      dockerfile: conf_docker/php/Dockerfile
    container_name: meca-php
    volumes:
      - ./src:/var/www/html
    dns:
      - 192.168.11.75
    networks:
      - meca-network

  nginx:
    image: nginx:stable
    container_name: meca-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - meca-network

  mysql:
    image: mysql:8.0
    container_name: meca-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - meca-network

  phpmyadmin:
    image: phpmyadmin:5
    container_name: meca-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - meca-network
