[Interface]
Address = 192.168.100.2/32
PrivateKey = uC6sRSTLyA+xhRpRisY7XpdjfVwrauuM3PqrvgBSG30=
DNS=8.8.8.8, 8.8.4.4

[Peer]
PublicKey = 2AqRiDtRnm+fh4VofFP8Z5PSj6BUU1Z9rM4jmWSjjVg=
EndPoint = 46.218.58.86:500
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25