[Interface]
Address = 192.168.100.2/32
PrivateKey = uC6sRSTLyA+xhRpRisY7XpdjfVwrauuM3PqrvgBSG30=
DNS = 192.168.11.1

[Peer]
PublicKey = 2AqRiDtRnm+fh4VofFP8Z5PSj6BUU1Z9rM4jmWSjjVg=
Endpoint = 46.218.58.86:500
AllowedIPs = 192.168.11.0/24, 192.168.100.1/32
PersistentKeepalive = 25
