name: Deploy Docker Compose on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Restart containers
        run: docker compose up -d --remove-orphans

      - name: Check running containers
        run: docker compose ps

      - name: Cleanup unused images
        run: docker image prune -f
